### ISSUE TITLE
Migrate custom .css from Danube to Zambezi (triangular) WalkMe widget theme. 

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/walkme#21]
Users have requested that the walkme widget not cover the dashboard. @joshkoenig +1'ed a move to the triangular widget to be less intrusive. We'll need to modify the css in order to match our styles.

**Comment by bmackinney** [comment]
@informanddelight can we get the image design into your queue?

**Comment by informanddelight** [comment]
Wrote that into my sprint.ly UI backlog. I'll raise it up but I'm not sure
how it'll fit in the queue with kicking off some other projects next week:
https://sprint.ly/product/24230/item/2757

**Comment by bmackinney** [comment]
Complete
![](http://d2qkfn813cyz6e.cloudfront.net/images/pantheon-zambezisvg.svg)
